# Generated by Django 4.0.3 on 2022-03-31 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='s',
            new_name='id',
        ),
    ]
